export const departments = [
  'Computer Science',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Data Science',
  'Information Systems',
  'Biomedical Engineering',
];

export const mockProjects = [
  {
    id: '1',
    title: 'AI-Powered Campus Navigation System',
    department: 'Computer Science',
    year: 2024,
    semester: 'Spring',
    status: 'completed',
    students: ['Alice Chen', 'Bob Martinez'],
    advisor: 'Dr. Sarah Johnson',
    summary: 'Developed a mobile-first indoor navigation system using computer vision and BLE beacons to help students navigate campus buildings. Achieved 92% accuracy in location detection.',
    tags: ['AI', 'Mobile', 'Computer Vision', 'IoT'],
    lessonsLearned: [
      'BLE beacon placement density critically affects accuracy',
      'Computer vision alone is insufficient for indoor navigation — hybrid approach needed',
      'User testing revealed preference for AR overlay vs 2D maps',
    ],
    challenges: [
      'Inconsistent BLE signal strength across different building materials',
      'High battery drain from continuous camera usage',
      'Limited training data for campus-specific landmarks',
    ],
    failedApproaches: [
      'Pure WiFi fingerprinting — too unreliable due to dynamic network changes',
      'GPS-only approach — no indoor coverage',
    ],
    futureWork: [
      'Extend to outdoor campus areas with seamless handoff',
      'Add accessibility features for visually impaired students',
      'Integrate with class schedule for smart routing',
    ],
    tools: ['React Native', 'TensorFlow Lite', 'Firebase', 'Python'],
  },
  {
    id: '2',
    title: 'Smart Energy Monitoring Dashboard',
    department: 'Electrical Engineering',
    year: 2024,
    semester: 'Fall',
    status: 'incomplete',
    students: ['David Kim', 'Eva Patel'],
    advisor: 'Prof. Michael Lee',
    summary: 'Built a real-time energy monitoring dashboard for campus buildings using IoT sensors. Successfully deployed in 3 buildings but ran out of time for predictive analytics module.',
    tags: ['IoT', 'Dashboard', 'Energy', 'Sustainability'],
    lessonsLearned: [
      'Sensor calibration is more time-consuming than anticipated',
      'Real-time data streaming requires careful architecture planning',
      'Stakeholder buy-in from facilities management is crucial early on',
    ],
    challenges: [
      'Legacy building electrical systems lack standard interfaces',
      'Data volume exceeded initial database design capacity',
    ],
    failedApproaches: [
      'Direct sensor-to-cloud architecture — latency issues, switched to edge computing',
    ],
    futureWork: [
      'Complete the predictive analytics module using LSTM networks',
      'Expand to remaining 12 campus buildings',
      'Add anomaly detection for equipment failure prediction',
    ],
    tools: ['Arduino', 'MQTT', 'InfluxDB', 'Grafana', 'React'],
  },
  {
    id: '3',
    title: 'Blockchain-Based Academic Credential Verification',
    department: 'Information Systems',
    year: 2023,
    semester: 'Spring',
    status: 'failed',
    students: ['Frank Liu', 'Grace Wang'],
    advisor: 'Dr. Emily Brown',
    summary: 'Attempted to build a decentralized system for verifying academic credentials using blockchain. Project was technically functional but failed due to institutional adoption barriers.',
    tags: ['Blockchain', 'Security', 'Credentials'],
    lessonsLearned: [
      'Technical feasibility does not equal institutional readiness',
      'Regulatory compliance requirements were underestimated',
      'Simpler solutions (digital signatures) may be more practical',
    ],
    challenges: [
      'Gas costs on Ethereum mainnet were prohibitive',
      'No standard schema for academic credentials across institutions',
      'Privacy concerns with immutable public records',
    ],
    failedApproaches: [
      'Public Ethereum mainnet — costs too high, switched to private chain',
      'Storing full credentials on-chain — storage limitations',
    ],
    futureWork: [
      'Explore W3C Verifiable Credentials standard instead',
      'Consider consortium blockchain approach with partner universities',
      'Implement zero-knowledge proofs for privacy',
    ],
    tools: ['Solidity', 'Hardhat', 'React', 'IPFS', 'Node.js'],
  },
  {
    id: '4',
    title: 'Predictive Student Performance Analytics',
    department: 'Data Science',
    year: 2024,
    semester: 'Spring',
    status: 'completed',
    students: ['Hannah Park', 'Ian Ross'],
    advisor: 'Dr. James Wilson',
    summary: 'Created a machine learning pipeline that predicts at-risk students with 87% accuracy using anonymized LMS engagement data, enabling early intervention by academic advisors.',
    tags: ['Machine Learning', 'Education', 'Analytics', 'Python'],
    lessonsLearned: [
      'Feature engineering from LMS data was the biggest accuracy driver',
      'Ethical review board approval took 6 weeks — plan ahead',
      'Simple models (gradient boosting) outperformed deep learning for this dataset size',
    ],
    challenges: [
      'Data anonymization while preserving analytical value',
      'Imbalanced classes — only 15% of students are at-risk',
      'Explaining model predictions to non-technical advisors',
    ],
    failedApproaches: [
      'Deep learning approach — overfitting on small dataset',
      'Using only grade data — insufficient signal without engagement metrics',
    ],
    futureWork: [
      'Integrate with student information system for real-time alerts',
      'Add natural language feedback from advisor interactions',
      'Expand to predict specific intervention strategies',
    ],
    tools: ['Python', 'scikit-learn', 'Pandas', 'Streamlit', 'PostgreSQL'],
  },
  {
    id: '5',
    title: 'Robotic Arm for Lab Automation',
    department: 'Mechanical Engineering',
    year: 2023,
    semester: 'Fall',
    status: 'continuation',
    students: ['Jack Thompson', 'Kelly Nguyen'],
    advisor: 'Prof. Robert Chen',
    summary: 'Designed and built a 6-DOF robotic arm for automating repetitive lab tasks. Mechanical design complete, software control system partially implemented.',
    tags: ['Robotics', 'Automation', 'CAD', 'Control Systems'],
    lessonsLearned: [
      '3D printed joints lack the precision needed — CNC milling recommended',
      'Inverse kinematics implementation is significantly more complex than forward',
      'Start with simulation before physical prototyping',
    ],
    challenges: [
      'Servo motor torque insufficient for heavier lab equipment',
      'Vibration at high speeds reduces precision',
    ],
    failedApproaches: [
      'PLA 3D printed gears — too fragile under repeated stress',
      'Open-loop control — drift accumulation made it unusable',
    ],
    futureWork: [
      'Implement closed-loop PID control with encoder feedback',
      'Add computer vision for object recognition and grasping',
      'Design custom PCB for motor controllers',
    ],
    tools: ['SolidWorks', 'Arduino', 'ROS', 'Python', 'MATLAB'],
    continuedFrom: 'Preliminary Robotic Arm Design (2023 Spring)',
  },
  {
    id: '6',
    title: 'Wearable Health Monitor for Athletes',
    department: 'Biomedical Engineering',
    year: 2024,
    semester: 'Fall',
    status: 'completed',
    students: ['Laura Smith', 'Mike Johnson'],
    advisor: 'Dr. Patricia Williams',
    summary: 'Developed a wearable device that monitors heart rate, body temperature, and hydration levels for university athletes. Successfully tested with the varsity track team.',
    tags: ['Wearable', 'Health', 'IoT', 'Signal Processing'],
    lessonsLearned: [
      'Sweat and motion artifacts are the biggest challenges in biometric sensing',
      'Battery life optimization requires aggressive duty cycling',
      'Athletes prefer minimal form factor over feature richness',
    ],
    challenges: [
      'Motion artifacts during high-intensity exercise',
      'Skin contact impedance varies significantly between individuals',
    ],
    failedApproaches: [
      'Optical hydration sensing — insufficient accuracy with current LEDs',
      'Rigid PCB design — uncomfortable during exercise, switched to flex PCB',
    ],
    futureWork: [
      'Add muscle fatigue detection using EMG',
      'Develop coaching app with personalized training recommendations',
      'Miniaturize the device for everyday wear',
    ],
    tools: ['KiCad', 'C++', 'BLE', 'Flutter', 'MATLAB'],
  },
];
